### ISSUE TITLE
Data Transformations and Code for Training

### ISSUE THREAD

**Issue by vnik18** [CogComp/faithful_summarization#1]
Hi,

I was wondering whether it is possible for you to share the code for producing unfaithful variants of ground truth summaries. Could you also please share your training script?

Thank you very much!

**Comment by schen149** [comment]
They will be updated in this repo in the next few days; Please stay tuned -- I'll reply to this thread again once they are ready. 

Here's the data we use for training + validation (unfaithful variants generated on XSum) -- 
https://drive.google.com/drive/folders/18Eqfemxf6wOQeSUNrZMlacF2OvwaRQ87?usp=sharing

**Comment by schen149** [comment]
Hi, 

I've uploaded the code for data transformation + training. Please refer to the readme for more details,

Thanks!
